### ISSUE TITLE
Looking at the examples - need to update them with the new registry details

### ISSUE THREAD

**Issue by chris-milsted** [RHC4TP/starter#1]
Looking at the example Docker files, they reference registry.access.redhat.com which is going to be transitioned to registry.redhat.io and registry.connect.redhat.io in the future as per the article here:

https://www.redhat.com/en/blog/transitioning-red-hat-container-registry

They will also need a guide on how to create a pull secret to automate this as the new registry needs authentication.

Example:

https://github.com/RHC4TP/starter/blob/master/Container%20Zone/Examples/WebServer_Dockerfile_RHEL

```
# Pull the rhel image from the local repository
FROM registry.access.redhat.com/rhel7/rhel
```

Need to update the files and steps with these new registries.

Thanks

**Comment by gfranchini** [comment]
Thanks for pointing this out. I have updated the templates to use the new registry link and added a note to the README. Much appreciated.
